version: '3.5'

services:

  notebookdb:
    image: postgres:13
    container_name: 'notebookdb'
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=notebookuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=notebookdb
    volumes:
      - notebook-data:/var/lib/postgresql/data
    networks:
      - local

volumes:
  notebook-data: { }

networks:
 local:
  driver: bridge