version: '3.5'

services:

  db:
    image: postgres:13
    container_name: 'db'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=notebookuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=notebookdb
    volumes:
      - notebook-data:/var/lib/postgresql/data

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notebookdb
      - SPRING_DATASOURCE_USERNAME=notebookuser
      - SPRING_DATASOURCE_PASSWORD=123456

  react-app:
    build:
      context: ./noteapp-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
volumes:
  notebook-data: { }