version: '3.5'

services:

  notebookdb:
    image: postgres:13
    container_name: 'notebookdb'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=notebookuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=notebookdb
    volumes:
      - notebook-data:/var/lib/postgresql/data
    networks:
      - local

  notebookbe:
    expose:
      - "8080"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'notebookbe'
    ports:
      - "8080:8080"
    env_file:
      - ./notebook.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notebookdb:5432/notebookdb
      - SPRING_DATASOURCE_USERNAME=notebookuser
      - SPRING_DATASOURCE_PASSWORD=123456
    networks:
      - local
      - notebookbe
    depends_on:
      - notebookdb


  notebookfe:
    expose:
      - "3000"
    build:
      context: ./noteapp-ui/
      dockerfile: Dockerfile
    container_name: 'note-app-ui'
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://notebookbe
      - REACT_APP_BACKEND_PORT=8080
    networks:
      - local
      - frontend
    depends_on:
      - notebookbe

  proxy:
    image: nginx:1.25.3
    container_name: "proxy"
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - notebookbe
      - notebookfe
    networks:
      - frontend

volumes:
  notebook-data: { }

networks:
  local:
    driver: bridge
  notebookbe:
    internal: true
  frontend:
    external: true